#!/usr/bin/env bash

set -euo pipefail

readonly ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly STATE_DIR="$ROOT_DIR/.local-lightning"
readonly APP_ENV="$STATE_DIR/app.env"
readonly COMPOSE=(docker compose --project-directory "$ROOT_DIR")

btc() {
  "${COMPOSE[@]}" exec -T bitcoin bitcoin-cli \
    -regtest \
    -rpcuser=skillsats \
    -rpcpassword=skillsats \
    "$@"
}

skillsats_ln() {
  "${COMPOSE[@]}" exec -T lnd-skillsats lncli --network=regtest "$@"
}

payer_ln() {
  "${COMPOSE[@]}" exec -T lnd-payer lncli --network=regtest "$@"
}

ensure_wallet() {
  local service="$1"
  local rest_url="$2"
  local attempts=0

  if "${COMPOSE[@]}" exec -T "$service" \
    test -f /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon; then
    return
  fi

  until curl --fail --silent --insecure "$rest_url/v1/genseed" >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    if ((attempts >= 60)); then
      echo "Timed out waiting for $service wallet initialization RPC." >&2
      return 1
    fi
    sleep 2
  done

  echo "Creating the disposable $service wallet..."
  local seed
  local password
  seed="$(
    curl --fail --silent --insecure "$rest_url/v1/genseed" | jq -c '.cipher_seed_mnemonic'
  )"
  password="$(printf 'skillsats-regtest-only' | base64 --wrap=0)"

  curl --fail --silent --show-error --insecure --request POST "$rest_url/v1/initwallet" \
    --header "Content-Type: application/json" \
    --data "{\"wallet_password\":\"$password\",\"cipher_seed_mnemonic\":$seed}" >/dev/null
}

wait_for_lnd() {
  local service="$1"
  local attempts=0

  until "${COMPOSE[@]}" exec -T "$service" lncli --network=regtest getinfo >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    if ((attempts >= 90)); then
      echo "Timed out waiting for $service. Inspect logs with npm run lightning:logs." >&2
      return 1
    fi
    sleep 2
  done
}

wait_for_wallet_sync() {
  local attempts=0

  until [[ "$(payer_ln getinfo | jq -r '.wallet_synced')" == "true" ]]; do
    attempts=$((attempts + 1))
    if ((attempts >= 90)); then
      echo "Timed out waiting for the payer wallet to sync to Bitcoin Core." >&2
      return 1
    fi
    sleep 2
  done
}

ensure_miner_wallet() {
  if ! btc getwalletinfo >/dev/null 2>&1; then
    btc createwallet miner >/dev/null 2>&1 || btc loadwallet miner >/dev/null
  fi
}

mine_blocks() {
  local count="$1"
  local address
  address="$(btc getnewaddress)"
  btc generatetoaddress "$count" "$address" >/dev/null
}

ensure_channel() {
  local channel_count
  channel_count="$(payer_ln listchannels | jq '.channels | length')"
  if ((channel_count > 0)); then
    wait_for_active_channel
    return
  fi

  echo "Funding the payer node with regtest bitcoin..."
  ensure_miner_wallet

  local height
  height="$(btc getblockcount)"
  if ((height < 101)); then
    mine_blocks "$((101 - height))"
  fi

  local confirmed_balance
  confirmed_balance="$(payer_ln walletbalance | jq -r '.confirmed_balance | tonumber')"
  if ((confirmed_balance < 1100000)); then
    local payer_address
    payer_address="$(payer_ln newaddress p2wkh | jq -r '.address')"
    btc sendtoaddress "$payer_address" 0.02 >/dev/null
    mine_blocks 6
  fi

  wait_for_wallet_sync

  local skillsats_pubkey
  skillsats_pubkey="$(skillsats_ln getinfo | jq -r '.identity_pubkey')"

  payer_ln connect "${skillsats_pubkey}@lnd-skillsats:9735" >/dev/null 2>&1 || true

  echo "Opening a balanced 1,000,000 sat channel..."
  payer_ln openchannel \
    --node_key="$skillsats_pubkey" \
    --local_amt=1000000 \
    --push_amt=500000 \
    --sat_per_vbyte=1 >/dev/null
  mine_blocks 6
  wait_for_active_channel
}

wait_for_active_channel() {
  local attempts=0
  until (( $(payer_ln listchannels | jq '[.channels[] | select(.active)] | length') > 0 )); do
    attempts=$((attempts + 1))
    if ((attempts >= 60)); then
      echo "Timed out waiting for the Lightning channel to become active." >&2
      return 1
    fi
    sleep 2
  done
}

write_app_env() {
  local skillsats_macaroon
  local payer_macaroon
  skillsats_macaroon="$(
    "${COMPOSE[@]}" exec -T lnd-skillsats \
      xxd -p -c 1000 /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon | tr -d '\r\n'
  )"
  payer_macaroon="$(
    "${COMPOSE[@]}" exec -T lnd-payer \
      xxd -p -c 1000 /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon | tr -d '\r\n'
  )"

  cat >"$APP_ENV" <<EOF
# Generated by scripts/lightning-docker.sh. Regtest credentials only.
LND_REST_HOST="https://127.0.0.1:8080"
LND_MACAROON="$skillsats_macaroon"
LND_MACAROON_PATH=""
LND_TLS_CERT_PATH=""
DEV_LND_PAYER_REST_HOST="https://127.0.0.1:8081"
DEV_LND_PAYER_MACAROON="$payer_macaroon"
DEV_LND_PAYER_MACAROON_PATH=""
DEV_LND_PAYER_TLS_CERT_PATH=""
EOF
  chmod 600 "$APP_ENV"
}

start_network() {
  mkdir -p "$STATE_DIR/lnd-skillsats" "$STATE_DIR/lnd-payer"

  echo "Starting Bitcoin Core and two LND nodes..."
  "${COMPOSE[@]}" --profile lightning up -d bitcoin lnd-skillsats lnd-payer

  ensure_wallet lnd-skillsats "https://127.0.0.1:8080"
  ensure_wallet lnd-payer "https://127.0.0.1:8081"
  wait_for_lnd lnd-skillsats
  wait_for_lnd lnd-payer
  ensure_channel
  write_app_env

  echo
  echo "Headless Lightning network is ready."
  echo "Run npm run dev:lightning to start SkillSats against it."
  echo "Run npm run lightning:check to inspect both nodes."
}

case "${1:-up}" in
  up)
    start_network
    ;;
  down)
    "${COMPOSE[@]}" --profile lightning stop lnd-payer lnd-skillsats bitcoin
    ;;
  logs)
    "${COMPOSE[@]}" --profile lightning logs -f bitcoin lnd-skillsats lnd-payer
    ;;
  reset)
    "${COMPOSE[@]}" --profile lightning stop lnd-payer lnd-skillsats bitcoin
    "${COMPOSE[@]}" --profile lightning rm -f lnd-payer lnd-skillsats bitcoin
    docker volume rm skillsats_bitcoin-regtest-data >/dev/null 2>&1 || true
    docker run --rm --entrypoint sh \
      --volume "$STATE_DIR:/state" \
      lightninglabs/lnd:v0.21.0-beta \
      -c 'rm -rf /state/* /state/.[!.]* /state/..?*' >/dev/null
    rmdir "$STATE_DIR" 2>/dev/null || true
    echo "Local regtest Lightning state removed."
    ;;
  *)
    echo "Usage: $0 {up|down|logs|reset}" >&2
    exit 1
    ;;
esac
